window.advancedTopicsDetails = {
  "How to launch my Business Online": [
    "Choose your business idea & define your niche.",
    "How to create your landing page or website in minutes using AI.",
    "How to set up an online store for your digital or physical product.",
    "Set up a professional website or landing page.",
    "Create social media accounts for your business.",
    "Set up email marketing tools & automation.",
    "Learn how to drive traffic to your store / website using Facebook ads.",
    "Set up online payment methods (Paystack, Flutterwave, etc.)",
    "Create and organize digital products or services.",
    "Implement basic analytics to track visitors & sales.",
    "Launch your business, promote it & engage your first customers.",
  ],

  "I want to learn how to run TikTok ads for my business": [
    "How to create and set up your TikTok Ads Manager.",
    "How to install TikTok Pixel on your website or landing page.",
    "How to pick the correct campaign objective.",
    "How to create TikTok-style short videos with native pacing.",
    "How to use hooks, trending formats, and text overlays.",
    "How to test multiple creatives at once (3–5 videos).",
    "How to identify strong CTR, CPC, and view duration.",
    "How to target interest + behavior audiences effectively.",
    "How to use automated creative optimization (ACO).",
    "How to scale winning TikTok ads profitably.",
  ],

  "How to start a profitable online business": [
    "How to pick a business model (digital products, affiliate marketing, freelancing, e-commerce, coaching, etc.)",
    "How to choose a clear niche for your business (fitness, fashion, tech, skincare, digital marketing, etc.)",
    "How to validate the niche by checking demand using Google Trends, TikTok search, YouTube search, Amazon, etc.",
    "How to build your online presence (website, landing page, portfolio, or social media business pages) using AI.",
    "How to create your main offer — what exactly people will buy from you.",
    "How to set up online payment methods (Paystack, Flutterwave, Monnify, etc.)",
    "How to create a traffic system to attract customers (TikTok, Instagram Reels, YouTube, Facebook ads, etc.)",
    "How to launch your business — post content, share your offer, promote it daily via sponsored ads.",
    "How to optimize and scale once you make your first sales (improve offers, run ads, build email list).",
    "The needs to add more products/services and reinvesting in marketing.",
  ],

  "WhatsApp Sales Automation Setup": [
    "How to create a pre-sales message script.",
    "How to set up WhatsApp Business with auto-reply.",
    "How to integrate bot to chat with your customers or audiences.",
    "How to organize broadcast lists by interest type.",
    "How to use catalogue feature to show products/services.",
    "Adding quick replies for FAQs.",
    "How to run a Click-to-WhatsApp Facebook / instagram ads.",
    "How to set up keyword triggers using an automation tool.",
    "How to collect leads using WhatsApp chat links.",
    "How  to use templates to speed up responses.",
    "How to track leads through a simple CRM or Google Sheet.",
  ],

  "I want to learn how to run Instagram ads specifically": [
    "How to switch your account to a Professional/Business account.",
    "How to connect your Instagram page to your Facebook Business Manager.",
    "How to choose Instagram-focused campaign objectives.",
    "How to select only Instagram placements (Reels, Feed, Stories, Explore).",
    "How to design Instagram-formatted creatives (1:1, 4:5, 9:16).",
    "How to write captions that fit Instagram culture.",
    "How to test multiple creatives for Reels and Feed separately.",
    "How to analyze Instagram ad metrics like saves, shares, profile visits.",
    "How to use deep-interest targeting for IG audiences.",
    "How to scale the best performing Instagram ads.",
  ],

  "Fixing Low Engagement on Ads or post": [
    "How to check if your creative is too text-heavy.",
    "How to optimize your post or ads with AI for 100% engagment.",
    "How to use relatable human visuals instead of generic stock photos.",
    "Switching to short-form video (UGC-style).",
    "How to make your headline more attention-grabbing.",
    "How shorten your caption and add strong hooks.",
    "How to run ads to engagement audiences first.",
    "How to use emojis to enhance emotion and readability.",
    "Testing multiple colors, layouts, and angles.",
    "How to retarget viewers with stronger content.",
    "Refresh creatives every 5–7 days.",
  ],

  "Boosting Website Conversion Rate": [
    "How to create your conversion landing page or website in minutes using AI.",
    "How to simplify your landing page layout.",
    "How to install Facebook Pixel on your website / landing page to track visitor actions.",
    "How to add clear visual hierarchy (big headline, bold CTA).",
    "How to use high-quality product/service images.",
    "How to add testimonials and trust badges.",
    "How to improve page loading speed.",
    "The right way to add scarcity elements like limited spots.",
    "How to use sticky CTA button on mobile.",
    "Write clear benefits-driven copy.",
    "Removing unnecessary distractions or links.",
    "A/B test different versions of your page.",
  ],

  "How to Setup Custom Audience Using AI": [
    "Define your business goal – decide whether you want conversions, leads, or traffic.",
    "Install the Facebook Pixel on your website to track visitor actions.",
    "Collect first-party data: website visitors, app users, email subscribers or CRM contacts.",
    "Create a Custom Audience in Ads Manager: Audiences → Create Audience → Custom Audience; select Website Traffic, Customer List, or App Activity; use AI-powered segmentation.",
    "Leverage Lookalike Audiences based on your best customers or high-value users; select audience size (1–10%) for reach vs precision; Facebook AI identifies similar users likely to convert.",
    "Use AI-driven Audience Expansion: enable Detailed Targeting Expansion in Ad Set to find additional people outside selected criteria who may perform well.",
    "Layer demographic & interest targeting (optional): age, gender, location, languages, behaviors, interests, online activity patterns.",
    "Test multiple audiences: split test different custom audiences; AI will automatically optimize delivery over time.",
    "Monitor performance & adjust using Ads Manager analytics; refine audiences based on AI recommendations and results.",
    "Advantages of using AI for audiences: reduces wasted ad spend by targeting likely converters; finds new potential customers automatically; improves ad relevance and ROI.",
  ],

  "Fixing Facebook Ad Rejection & Policy Violations": [
    "Check the exact rejection reason in Ads Manager.",
    "Review Facebook's policy article related to the reason.",
    "Edit ad creative (images/videos) that trigger policy flags.",
    "Rewrite ad copy to remove prohibited or sensational language.",
    "Validate landing page content and remove disallowed claims.",
    "Remove any targeting or offers that violate local rules.",
    "Resubmit the ad and monitor review status.",
    "If rejected again, gather screenshots and submit an appeal.",
    "Document the change so future ads avoid the same issue.",
    "Consider using a different creative approach and re-test.",
  ],
  "Recovering Disabled Facebook Ad Accounts": [
    "Visit Account Quality and read the reason for disablement.",
    "Gather business documents if required (CAC, ID, etc.).",
    "Open the appeal form and provide a clear explanation.",
    "Avoid creating a new ad account while the appeal is in progress.",
    "Check payment methods — remove any problematic cards.",
    "Audit past ads for policy violations and remove offending creatives.",
    "Ask colleagues to check page roles for suspicious users.",
    "Follow up in Account Quality or Business Help Center if no reply.",
    "Complete Business Verification if Facebook requests proof.",
    "After restoration, implement internal ad approval controls.",
  ],
  "Fixing Restricted Business Manager Access": [
    "Identify which asset is restricted (page/ad account/pixel).",
    "Check user roles and remove suspicious or duplicate admins.",
    "Complete Business Verification in Business Manager if required.",
    "Confirm ownership of connected assets (pages, domains).",
    "Resolve any outstanding policy issues on pages or ad accounts.",
    "Request access from the asset owner with clear justification.",
    "If access was removed, contact the asset owner and Facebook support.",
    "Ensure billing and contact information are valid and up to date.",
    "Document the reconfiguration steps so the team knows what changed.",
    "Create a backup admin user to avoid single-point-of-failure.",
  ],
  "How to Reduce High Cost-Per-Result (CPR)": [
    "Run a performance breakdown to find the highest CPR ad sets.",
    "Pause or rework low-performing creatives and audiences.",
    "Test alternative audiences with better intent signals.",
    "Improve landing pages to increase conversion rate.",
    "Experiment with different bidding strategies (lowest cost vs bid cap).",
    "Use retargeting for low-funnel audiences where CPR is cheaper.",
    "Try new placements and automatic placements for cheaper delivery.",
    "Split-test ad creative variations to improve CTR and CVR.",
    "Scale gradually when you see winning combinations to keep CPR stable.",
    "Monitor and iterate daily until CPR stabilizes at target level.",
  ],
  "How to Reduce High CPM": [
    "Narrow or refine audience relevance to reduce wasted impressions.",
    "Improve creative and headline to increase engagement (CTR lowers CPM).",
    "Rotate creatives frequently to avoid ad fatigue and high frequency.",
    "Test lookalike audiences to find cheaper but relevant reach.",
    "Use automatic placements and then refine if needed.",
    "Schedule ads during times of day when CPMs historically dip.",
    "Increase audience size slightly to let the auction find cheaper users.",
    "Avoid audience overlap between ad sets to reduce internal competition.",
    "Review and test different ad formats (video often performs better).",
    "Use broad targeting + strong creatives for algorithmic optimization.",
  ],
  "Advanced Target Audience Research": [
    "Use Facebook Audience Insights and your analytics data to profile customers.",
    "Analyze top competitors’ audiences for targeting and creative cues.",
    "Build layered custom audiences (website visitors, purchasers, engagers).",
    "Create lookalikes from high-value customer lists, not all users.",
    "Segment audiences by lifecycle stage and tailor creatives.",
    "Test interest and behavior stacks to find high-performing combos.",
    "Exclude existing customers or irrelevant groups from acquisition sets.",
    "Use demographic and geolocation filters to focus spend.",
    "Track audience performance and keep a list of winning segments.",
    "Document audiences and maintain a naming convention for reuse.",
  ],
  "How to Fix Ads Not Spending": [
    "Confirm ads are approved and not stuck in review.",
    "Check campaign budget and schedule — ensure budgets aren't zero.",
    "Inspect targeting for over-restriction (too narrow audiences).",
    "Review bid strategy — ensure bids are realistic for the market.",
    "Verify payment method (card not expired, sufficient funds).",
    "Enable automatic placements to let the system find delivery.",
    "Duplicate and simplify the ad set to test delivery quickly.",
    "Check for conflicts: excluded audiences overlapping with included.",
    "Look at delivery diagnostics in Ads Manager for errors.",
    "Contact Facebook support if the ad set still refuses to spend.",
  ],
  "How to Scale Winning Ads Profitably": [
    "Identify true winners using stable metrics (ROAS, CPA over time).",
    "Scale budgets gradually (10–30% increments) instead of sudden jumps.",
    "Duplicate winning ad sets and test slightly larger audiences.",
    "Use lookalikes based on converters, not just visitors.",
    "Introduce new creatives to avoid fatigue while keeping the winning formula.",
    "Use CBO carefully for scaling funnels.",
    "Monitor frequency and CPA closely during scale-up.",
    "Leverage automated rules to scale or pause based on performance.",
    "Consider geographic scaling (start similar markets before wide expansion).",
    "Keep a rollback plan if performance degrades during scaling.",
  ],
  "Fixing Learning Limited Issues": [
    "What learning phase is amd how it works",
    "Understanding the learning phase thresholds for your objective.",
    "Increasing conversions per week by raising budget or widening audience.",
    "Avoid making multiple edits during the learning window.",
    "Combine ad sets with similar targeting to increase volume.",
    "Use the recommended conversion event to simplify optimization.",
    "Extend campaign timelines to gather more data before conclusions.",
    "Use automatic placements to maximize delivery opportunities.",
    "Run higher-quality creatives to improve relevance and delivery.",
    "If using CAPI, ensure server events are consistent with pixel events.",
    "Only make meaningful changes after the learning period completes.",
  ],
  "Best Campaign Structure for More Sales": [
    "How to set campaigns by objective (TOF, MOF, BOF) with clear KPIs.",
    "How to separate ad sets per audience segment for clean testing.",
    "How to group creatives by theme/product within ad sets.",
    "How to use use retargeting ad sets dedicated to past visitors and cart abandoners.",
    "How to create lookalikes from high-value buyers for cold traffic.",
    "Keeping budgets aligned with funnel stage (more at TOF, less at BOF).",
    "Using conversion-focused objectives for BOF campaigns.",
    "How to test different placements and allocate budget to best performers.",
    "Tracking performance by campaign to know where to scale or pause.",
    "When / how to refresh creatives and messaging for each funnel stage.",
  ],
  "A/B Creative Testing Strategy": [
    "How to decide the single variable to test (headline, image, copy, CTA).",
    "How to create variations with clear naming conventions.",
    "How to run tests with the same audience to avoid external bias.",
    "The right way to measure CTR, CVR and CPA to identify winners.",
    "Pausing losers early and reallocate budget to winners.",
    "How to iterate on winning creatives and re-run new tests.",
    "How to use multiple formats (video, carousel) to spot format winners.",
    "How to automate reporting so tests are tracked and documented.",
    "How to scale winners into broader audiences cautiously.",
    "Keeping a library of winning creative combos for reuse.",
  ],
  "Fixing Low Reach / Shadow Bans": [
    "How to check Account Quality for any restrictions or flags.",
    "How to review content for policy violations or spammy language.",
    "How to reduce repeated identical creatives to avoid spam signals.",
    "Diversifying creatives and ad text to improve authenticity.",
    "Verifying payment methods and billing information.",
    "Appealing via Account Quality if you suspect wrongful restriction.",
    "How to temporarily lowering spend and then reintroducing ads.",
    "How to test ads in a new ad account (only if allowed and safe).",
    "Monitoring reach metrics after changes to confirm recovery.",
    "Documenting steps taken for future reference.",
  ],
};

// payment map for advanced topics (Naira numbers)
window.advancedTopicsPayment = {
  "Fixing Facebook Ad Rejection & Policy Violations": 8500,
  "Recovering Disabled Facebook Ad Accounts": 8000,
  "Fixing Restricted Business Manager Access": 7500,
  "How to Reduce High Cost-Per-Result (CPR)": 15000,
  "How to Reduce High CPM": 10000,
  "Boosting Website Conversion Rate": 15000,
  "How to Setup Custom Audience Using AI": 15000,
  "How to launch my Business Online": 15000,
  "Advanced Target Audience Research": 8000,
  "How to Fix Ads Not Spending": 15000,
  "Fixing Low Engagement on Ads or post": 15000,
  "How to Scale Winning Ads Profitably": 15000,
  "Fixing Learning Limited Issues": 15000,
  "Best Campaign Structure for More Sales": 12000,
  "A/B Creative Testing Strategy": 10000,
  "Fixing Low Reach / Shadow Bans": 12000,
  "WhatsApp Sales Automation Setup": 20000,
  "I want to learn how to run Instagram ads specifically": 7500,
  "I want to learn how to run TikTok ads for my business": 7500,
  "How to start a profitable online business": 15000,
};
